name: deploy-mdb-atlas-app-service
run-name: ${{ github.actor }} is learning Atlas App Service
on: [workflow_dispatch]
jobs:
  build-svelte:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm i
        working-directory: ./atlas-hosting 
      - run: npm run build
        working-directory: ./atlas-hosting
      - run: mkdir -p ./data/hosting/files
      - run: cp -R ./atlas-hosting/build/* ./data/hosting/files
      - uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: ./data
  deploy-svelte:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install mongodb-realm-cli
      - uses: actions/download-artifact@v3
        with:
          name: build-artifact
      - run: ls -lah